"""A1 수준 기초 단어 시드.

외부 무료 소스(Instituto Cervantes PCIC, Wiktionary, RAE 등)는 공식 API가
없거나 성(gender) 정보 또는 한국어 뜻이 없어, 저장소에 직접 큐레이션해 번들한다.

성 규칙:
- 명사가 아닌 것(동사·형용사·부사·인사 표현) → none
- 남/여 동형 사람 명사 (el/la estudiante) → n
- 그 외 명사 → m/f, 단수 원형만
- 뜻이 여러 개면 쉼표 구분 (채점기의 대안 뜻 분리와 호환)
"""

import db

# (word, gender, meaning)
SEED_WORDS = [
    # ── 인사·기본 표현 ──
    ("hola", "none", "안녕, 안녕하세요"),
    ("adiós", "none", "잘 가, 안녕히 가세요"),
    ("gracias", "none", "고마워, 감사합니다"),
    ("por favor", "none", "부탁합니다, 제발"),
    ("perdón", "none", "미안합니다, 실례합니다"),
    ("sí", "none", "네, 응"),
    ("no", "none", "아니요, 아니"),
    # ── 사람·가족 ──
    ("familia", "f", "가족"),
    ("padre", "m", "아버지"),
    ("madre", "f", "어머니"),
    ("hijo", "m", "아들"),
    ("hija", "f", "딸"),
    ("hermano", "m", "형, 오빠, 남동생"),
    ("hermana", "f", "누나, 언니, 여동생"),
    ("abuelo", "m", "할아버지"),
    ("hombre", "m", "남자"),
    ("mujer", "f", "여자, 아내"),
    ("niño", "m", "남자아이, 어린이"),
    ("amigo", "m", "친구"),
    ("persona", "f", "사람"),
    ("nombre", "m", "이름"),
    ("profesor", "m", "선생님, 교사"),
    # ── 양성 명사 (남/여 동형) ──
    ("estudiante", "n", "학생"),
    ("turista", "n", "관광객"),
    ("artista", "n", "예술가"),
    ("cantante", "n", "가수"),
    ("periodista", "n", "기자"),
    ("policía", "n", "경찰"),
    ("joven", "n", "젊은이, 젊은"),
    ("modelo", "n", "모델"),
    # ── 집·물건 ──
    ("casa", "f", "집"),
    ("puerta", "f", "문"),
    ("mesa", "f", "탁자, 테이블"),
    ("silla", "f", "의자"),
    ("cama", "f", "침대"),
    ("cocina", "f", "부엌, 주방"),
    ("baño", "m", "화장실, 욕실"),
    ("habitación", "f", "방"),
    ("teléfono", "m", "전화, 전화기"),
    ("ordenador", "m", "컴퓨터"),
    ("libro", "m", "책"),
    ("ropa", "f", "옷"),
    ("zapato", "m", "신발, 구두"),
    ("pantalón", "m", "바지"),
    ("regalo", "m", "선물"),
    ("carta", "f", "편지, 카드"),
    ("dinero", "m", "돈"),
    ("cosa", "f", "것, 물건"),
    # ── 음식 ──
    ("comida", "f", "음식, 식사"),
    ("agua", "f", "물"),
    ("pan", "m", "빵"),
    ("leche", "f", "우유"),
    ("café", "m", "커피"),
    ("té", "m", "차"),
    ("carne", "f", "고기"),
    ("pescado", "m", "생선"),
    ("pollo", "m", "닭고기, 닭"),
    ("huevo", "m", "달걀, 계란"),
    ("arroz", "m", "쌀, 밥"),
    ("fruta", "f", "과일"),
    ("manzana", "f", "사과"),
    ("cena", "f", "저녁 식사"),
    ("restaurante", "m", "식당, 레스토랑"),
    # ── 동물 ──
    ("perro", "m", "개, 강아지"),
    ("gato", "m", "고양이"),
    ("pájaro", "m", "새"),
    ("animal", "m", "동물"),
    # ── 신체 ──
    ("cabeza", "f", "머리"),
    ("ojo", "m", "눈"),
    ("nariz", "f", "코"),
    ("boca", "f", "입"),
    ("mano", "f", "손"),
    ("pie", "m", "발"),
    ("pelo", "m", "머리카락"),
    ("corazón", "m", "심장, 마음"),
    ("cuerpo", "m", "몸"),
    # ── 도시·장소 ──
    ("ciudad", "f", "도시"),
    ("calle", "f", "길, 거리"),
    ("tienda", "f", "가게, 상점"),
    ("mercado", "m", "시장"),
    ("banco", "m", "은행, 벤치"),
    ("hospital", "m", "병원"),
    ("escuela", "f", "학교"),
    ("universidad", "f", "대학교"),
    ("parque", "m", "공원"),
    ("estación", "f", "역, 정거장"),
    ("playa", "f", "해변, 바닷가"),
    ("mar", "m", "바다"),
    ("país", "m", "나라, 국가"),
    ("mundo", "m", "세계, 세상"),
    ("trabajo", "m", "일, 직장"),
    ("clase", "f", "수업, 교실"),
    ("examen", "m", "시험"),
    # ── 교통·여행 ──
    ("coche", "m", "자동차, 차"),
    ("autobús", "m", "버스"),
    ("tren", "m", "기차"),
    ("avión", "m", "비행기"),
    ("bicicleta", "f", "자전거"),
    ("taxi", "m", "택시"),
    ("viaje", "m", "여행"),
    # ── 시간 ──
    ("día", "m", "날, 하루"),
    ("noche", "f", "밤"),
    ("mañana", "f", "아침, 내일"),
    ("tarde", "f", "오후, 저녁"),
    ("semana", "f", "주, 일주일"),
    ("mes", "m", "달, 월"),
    ("año", "m", "년, 해"),
    ("hora", "f", "시간, 시"),
    ("tiempo", "m", "시간, 날씨"),
    ("hoy", "none", "오늘"),
    ("ayer", "none", "어제"),
    ("ahora", "none", "지금"),
    ("lunes", "m", "월요일"),
    ("martes", "m", "화요일"),
    ("miércoles", "m", "수요일"),
    ("jueves", "m", "목요일"),
    ("viernes", "m", "금요일"),
    ("sábado", "m", "토요일"),
    ("domingo", "m", "일요일"),
    # ── 자연·날씨 ──
    ("sol", "m", "해, 태양"),
    ("luna", "f", "달"),
    ("cielo", "m", "하늘"),
    ("lluvia", "f", "비"),
    ("nieve", "f", "눈(날씨)"),
    ("flor", "f", "꽃"),
    ("árbol", "m", "나무"),
    # ── 색 (형용사) ──
    ("rojo", "none", "빨간, 빨강"),
    ("azul", "none", "파란, 파랑"),
    ("blanco", "none", "하얀, 흰색"),
    ("negro", "none", "검은, 검정"),
    # ── 숫자 ──
    ("uno", "none", "하나, 1"),
    ("dos", "none", "둘, 2"),
    ("tres", "none", "셋, 3"),
    ("cuatro", "none", "넷, 4"),
    ("cinco", "none", "다섯, 5"),
    ("seis", "none", "여섯, 6"),
    ("siete", "none", "일곱, 7"),
    ("ocho", "none", "여덟, 8"),
    ("nueve", "none", "아홉, 9"),
    ("diez", "none", "열, 10"),
    # ── 동사 ──
    ("ser", "none", "~이다"),
    ("estar", "none", "있다, ~한 상태이다"),
    ("tener", "none", "가지다, 있다"),
    ("hacer", "none", "하다, 만들다"),
    ("ir", "none", "가다"),
    ("venir", "none", "오다"),
    ("ver", "none", "보다"),
    ("comer", "none", "먹다"),
    ("beber", "none", "마시다"),
    ("hablar", "none", "말하다, 이야기하다"),
    ("escuchar", "none", "듣다"),
    ("leer", "none", "읽다"),
    ("escribir", "none", "쓰다"),
    ("estudiar", "none", "공부하다"),
    ("aprender", "none", "배우다"),
    ("trabajar", "none", "일하다"),
    ("vivir", "none", "살다"),
    ("dormir", "none", "자다"),
    ("comprar", "none", "사다"),
    ("abrir", "none", "열다"),
    ("entrar", "none", "들어가다"),
    ("salir", "none", "나가다, 나오다"),
    ("llegar", "none", "도착하다"),
    ("buscar", "none", "찾다, 검색하다"),
    ("dar", "none", "주다"),
    ("tomar", "none", "잡다, 마시다, 타다"),
    ("poner", "none", "놓다, 두다"),
    ("querer", "none", "원하다, 사랑하다"),
    ("poder", "none", "할 수 있다"),
    ("saber", "none", "알다"),
    ("ayudar", "none", "돕다"),
    ("llamar", "none", "부르다, 전화하다"),
    ("pensar", "none", "생각하다"),
    ("gustar", "none", "좋아하다, 마음에 들다"),
    ("jugar", "none", "놀다, 경기하다"),
    # ── 형용사 ──
    ("grande", "none", "큰"),
    ("pequeño", "none", "작은"),
    ("bueno", "none", "좋은, 착한"),
    ("malo", "none", "나쁜"),
    ("nuevo", "none", "새, 새로운"),
    ("fácil", "none", "쉬운"),
    ("difícil", "none", "어려운"),
    ("frío", "none", "차가운, 추운"),
    ("caro", "none", "비싼"),
    ("barato", "none", "싼, 저렴한"),
    ("rápido", "none", "빠른"),
    ("feliz", "none", "행복한"),
    ("triste", "none", "슬픈"),
    ("mucho", "none", "많은"),
    ("poco", "none", "적은, 조금"),
    ("todo", "none", "모든, 전부"),
    ("otro", "none", "다른, 또 하나의"),
    # ── 부사·의문사·접속사 ──
    ("aquí", "none", "여기"),
    ("bien", "none", "잘, 좋게"),
    ("muy", "none", "매우, 아주"),
    ("más", "none", "더, 더 많이"),
    ("también", "none", "~도, 또한"),
    ("pero", "none", "그러나, 하지만"),
    ("porque", "none", "왜냐하면, ~때문에"),
    ("qué", "none", "무엇, 뭐"),
    ("quién", "none", "누구"),
    ("cuándo", "none", "언제"),
    ("dónde", "none", "어디, 어디에"),
    ("cómo", "none", "어떻게"),
    # ── 언어·나라 ──
    ("español", "m", "스페인어"),
    ("inglés", "m", "영어"),
    ("coreano", "m", "한국어"),
    ("españa", "f", "스페인"),
    ("corea", "f", "한국"),
    # ── 기타 명사 ──
    ("palabra", "f", "단어, 말"),
    ("pregunta", "f", "질문"),
    ("problema", "m", "문제"),
    ("música", "f", "음악"),
    ("número", "m", "숫자, 번호"),
    ("amor", "m", "사랑"),
    ("vida", "f", "삶, 인생, 생활"),
    ("ayuda", "f", "도움"),
    ("sueño", "m", "잠, 꿈"),
]


def seed_if_empty():
    """words 테이블이 완전히 비어 있을 때만 시드 삽입.

    비어 있지 않으면 아무것도 하지 않는다 — 사용자가 시드 단어를
    지웠을 때 재시작마다 되살아나지 않게 하기 위함.
    """
    with db.get_connection() as conn:
        count = conn.execute("SELECT COUNT(*) FROM words").fetchone()[0]
        if count:
            return
        conn.executemany(
            "INSERT INTO words (word, gender, meaning, norm) VALUES (?, ?, ?, ?)",
            [(w, g, m, db.normalize_word(w)) for w, g, m in SEED_WORDS],
        )
